
services:
  # cp-nifty-analyzer:
  #   build: .
  #   container_name: cp-nifty-analyzer
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://postgres:password@cp-nifty-postgres:5432/postgres
  #   depends_on:
  #     - postgres
  #   networks:
  #     - cp-nifty-network

  postgres:
    image: postgres:15
    container_name: cp-nifty-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cp-nifty-network


volumes:
  postgres_data:

networks:
  cp-nifty-network:
    driver: bridge