version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cp-nifty-postgres
    environment:
      POSTGRES_DB: cp-nifty-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cp-nifty-network


volumes:
  postgres_data:

networks:
  cp-nifty-network:
    driver: bridge